# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 10000
evaluation_epsilon: 0.0

runner: "episode"
batch_size_run: 1

buffer_size: 1000

# TEST PURPOSES ONLY
# batch_size: 2 # Number of episodes to train on

# update the target network every {} episodes
target_update_interval_or_tau: 20


obs_agent_id: True
# obs_last_action: False
# obs_individual_obs: False


# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True

agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "qmix"
# use_rnn: False
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "qmix"
on_policy: False