base_results_path: "./naht_results" # default location to save results
base_unseen_path: "./unseen_agents" # default location from which uncontrolled agents will be referenced
email: null # user email for condor notifications
